highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: html
    css_class: "syntax"

title: "Alessandro Lorenzi"
url: "https://alorenzi.eu"
media_url: "https://alessandrolorenzi5-546101540.imgix.net"

plugins:
  - jekyll-minifier
  - jekyll-toc

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      author: "Alessandro Lorenzi"
      layout: "post"
      toc: true
